name: Update Waka Readme

on:
  schedule:
    - cron: '10 0,6,12,18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
          SHOW_OS: "False"
          # Show Language Data
          SHOW_LANGUAGE: "True"
          SHOW_PROJECTS: "False"
          # Show GitHub Data
          SHOW_SHORT_INFO: "False"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          SHOW_TIMEZONE: "False"
          LOCALE: "zh"

  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist with WakaTime stats
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIST_ID: "595eec8ae8745b516c9a8ad8a265a100"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
